"""empty message

Revision ID: 6c05537a2471
Revises: 1be6f413b369
Create Date: 2022-12-11 23:17:58.612897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c05537a2471'
down_revision = '1be6f413b369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('inviter', sa.Integer(), nullable=True),
    sa.Column('invitee', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invitee'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inviter'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    # ### end Alembic commands ###